---
title: "Lab 04"
subtitle: "Due Feb 14 5:00 PM PST"
author: "Brandon Cho - 301365816"
format: html
---

# Problem 1a


```{r}
## write your answer here
my_lm <- function(x, y) {
  
  # use least squares regression formula
  x_mean <- mean(x)
  y_mean <- mean(y)
  
  slope <- sum((x - x_mean) * (y - y_mean)) / sum((x - x_mean)^2)
  y_intercept <- y_mean - (slope * x_mean)
  
  return(list(slope = slope, y_intercept = y_intercept))
  
}

```


## Problem 1b

In this problem both functions return identical values.

```{r}
## write answer here

# my function
first_three <- c(3, 0, 1)
last_three <- c(8, 1, 6)

result_my_lm <- my_lm(first_three, last_three)

result_my_lm$slope
result_my_lm$y_intercept


# R's function
model <- lm(y ~ x, data = data.frame(x = first_three, y = last_three))
alpha <- summary(model)$coefficients[1, 1]
beta <- summary(model)$coefficients[2, 1]

alpha
beta

```


## Problem 2a



```{r}
#| warning: false
## write answer here
library(RSQLite)
library(DBI)

db <- dbConnect(SQLite(), dbname = "xcoretail.sqlite")

months <- c("2011-01", "2011-02", "2011-03", "2011-04", "2011-05", "2011-06", "2011-07", "2011-08")
counts <- rep(NA, 8)

for (i in 1:8) {
  query <- paste0("
    SELECT SUM(sales.Quantity * prices.UnitPrice) AS total_revenue
    FROM sales
    JOIN prices ON sales.StockCode = prices.StockCode
    WHERE sales.StockCode = '71053' 
    AND sales.InvoiceDate LIKE '", months[i], "%'
  ")
  result <- dbGetQuery(db, query)
  counts[i] <- result$total_revenue
}

plot(1:8, counts, pch = 19,
     main = "Revenue for Product 71053 (Jan - Aug 2011)",
     xlab = "Month", ylab = "Revenue (USD)")

dbDisconnect(db)
```



## Problem 2b


```{r}
#| warning: false
## write answer here
db <- dbConnect(SQLite(), dbname = "xcoretail.sqlite")

counts <- rep(NA, 8)

for (i in 1:8) {
  query <- paste0("
    SELECT SUM(sales.Quantity * prices.UnitPrice) AS total_revenue
    FROM sales
    JOIN prices ON sales.StockCode = prices.StockCode
    WHERE sales.InvoiceDate LIKE '", months[i], "%'
  ")
  result <- dbGetQuery(db, query)
  counts[i] <- result$total_revenue
}

plot(1:8, counts, pch = 19,
     main = "Revenue for All Products (Jan - Aug 2011)",
     xlab = "Month", ylab = "Revenue (USD)")

dbDisconnect(db)
```


